# Generated by Django 5.0.7 on 2024-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_source', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(db_index=True)),
            ],
        ),
    ]
